import test from 'node:test';
import assert from 'node:assert/strict';
import { BALANCE } from '../server/balance.js';
import { Game, RESEARCH, treatmentForce } from '../server/game.js';
import { MVP_ACCEPTANCE_SCENARIOS, acceptanceCoverage } from '../server/acceptance.js';
import { readFile } from 'node:fs/promises';

const close=(actual,expected,epsilon=1e-6)=>assert.ok(Math.abs(actual-expected)<=epsilon,`${actual} != ${expected}`);
const gameOf=(columns=4,rows=1)=>{let id=0;return new Game({columns,rows,seed:'acceptance',id:()=>`acceptance-${++id}`});};
const pair=()=>{const game=gameOf(2),a=game.addPlayer('Alpha'),b=game.addPlayer('Beta');game.start(a,0);game.start(b,1);return {game,a,b};};

test('acceptance manifest maps all section 14 scenarios to explicit tests and client coverage',async()=>{
  const [spec,self,html,client]=await Promise.all([
    readFile(new URL('../GAMEPLAY_SPEC.md',import.meta.url),'utf8'),
    readFile(new URL('./mvp-acceptance.test.js',import.meta.url),'utf8'),
    readFile(new URL('../public/index.html',import.meta.url),'utf8'),
    readFile(new URL('../client/client.js',import.meta.url),'utf8')
  ]);
  const section=spec.match(/## 14\. MVP acceptance scenarios\n([\s\S]*?)\n## 15\./)?.[1]??'';
  assert.deepEqual([...section.matchAll(/^(\d+)\./gm)].map(match=>Number(match[1])),MVP_ACCEPTANCE_SCENARIOS.map(scenario=>scenario.id));
  for(const scenario of MVP_ACCEPTANCE_SCENARIOS)assert.match(self,new RegExp(`test\\('acceptance ${String(scenario.id).padStart(2,'0')}:`));
  assert.deepEqual(acceptanceCoverage(),{total:22,automated:0,complete:false,scenarios:MVP_ACCEPTANCE_SCENARIOS.map(scenario=>({...scenario,automated:false}))});
  assert.match(html,/id="acceptance-scenarios"/);assert.match(client,/state\.acceptance/);
});

test('acceptance 01: commissioned opening income and Balanced R02 timing [scenario:1]',()=>{const game=gameOf(),p=game.addPlayer();game.start(p,0);game.tick(5);close(p.net,10.3);for(let i=0;i<7;i++)game.tick(5);assert.ok(p.completed.includes('R02'));close(game.elapsed,40);close(p.researchProgress.R02,80);});
test('acceptance 02: level-one processing is capped before and after R01 [scenario:2]',()=>{const game=gameOf(),p=game.addPlayer();game.start(p,0);game.tick(.25);assert.ok(p.manufacturingSpend<=8);p.completed.push('R01');game.regions[0].inventories.medicine=0;game.tick(.25);assert.ok(p.manufacturingSpend<=8.8);});
test('acceptance 03: the budget ledger conserves one fixed-step grant [scenario:3]',()=>{const game=gameOf(),p=game.addPlayer();game.start(p,0);p.researchQueue=[];p.researchBank=125;p.allocation={research:40,manufacturing:60,infrastructure:0};game.regions[0].inventories.medicine=0;const before=p.revenue;game.tick(.25);const redirected=p.net*.25*.4;close(p.revenue-before,p.net*.25);close(p.researchBank,125);close(p.researchOverflow*.25,redirected);close(p.manufacturingFunding*.25,p.net*.25);close((p.manufacturingSpend+p.unusedManufacturing)*.25,p.net*.25);close(game.companyTelemetry(p).redirectedFunding,redirected);close(game.telemetry.totals.redirectedFunding,redirected);});
test('acceptance 04: research graph totals and minimum schedule are bounded [scenario:4]',()=>{assert.equal(Object.values(RESEARCH).reduce((sum,p)=>sum+p[2],0),2560);assert.equal(Object.values(RESEARCH).reduce((sum,p)=>sum+p[3],0),745);for(const [id,p] of Object.entries(RESEARCH))assert.notEqual(p[1],id);assert.ok(745>720);});
test('acceptance 05: percentage packets and ten-capacity minimum are exact [scenario:5]',()=>{const {game,a}=pair();game.regions[0].inventories.medicine=120;assert.equal(game.dispatch(a,0,1,50,'medicine'),true);close(game.convoys[0].supply.medicine,60);close(game.regions[0].inventories.medicine,60);const g=gameOf(2),p=g.addPlayer();g.start(p,0);p.completed.push('R04','R08','R09');g.regions[0].inventories.targeted=4;assert.equal(g.dispatch(p,0,1,100,'targeted'),true);const v=gameOf(2),q=v.addPlayer();v.start(q,0);q.completed.push('R09');v.regions[0].inventories.vaccine=2.5;assert.equal(v.dispatch(q,0,1,100,'vaccine'),true);});
test('acceptance 06: all-supply dispatch preserves manufacturing choice [scenario:6]',()=>{const {game,a}=pair();game.regions[0].inventories.medicine=20;game.regions[0].inventories.radiotherapy=10;const selected=a.selectedTreatment;game.dispatch(a,0,1,50,'all');close(game.convoys[0].supply.medicine,10);close(game.convoys[0].supply.radiotherapy,5);assert.equal(a.selectedTreatment,selected);assert.equal(game.convoys[0].edgeTime,5);});
test('acceptance 07: one routed command freezes three-edge travel timing [scenario:7]',()=>{for(const [r11,expected] of [[false,9],[true,7.5]]){const game=gameOf(4),p=game.addPlayer();game.start(p,0);for(const id of [1,2,3])game.regions[id].ownerId=p.id;if(r11){p.completed.push('R11');game.tick(.25);}game.regions[0].inventories.medicine=20;assert.equal(game.handle(p.id,{type:'dispatch',fromId:0,toId:3,commitment:50,filter:'medicine',commandId:`route-${r11}`}),true);while(!game.arrivalReports.length)game.tick(.25);assert.deepEqual(game.arrivalReports[0].convoyIds,['acceptance-3']);close(game.arrivalReports[0].at,expected);assert.equal(game.commandLog.filter(x=>x.message.type==='dispatch').length,1);}});
test('acceptance 08: source loss does not cancel a convoy and a broken route halts [scenario:8]',()=>{const game=gameOf(4),p=game.addPlayer();game.start(p,0);game.regions[1].ownerId=p.id;game.regions[2].ownerId=p.id;game.regions[3].ownerId=p.id;game.regions[0].inventories.medicine=20;game.dispatch(p,0,3,50,'medicine');game.regions[0].ownerId=null;game.regions[2].ownerId=null;game.tick(5);game.tick(1);assert.equal(game.routeInterruptions.length,1);});
test('acceptance 09: emitted pressure follows the conserved force equation [scenario:9]',()=>{const force=.1;close(BALANCE.contest.forceShare*force+Math.min(BALANCE.contest.flatPressureCap,force),.11);});
test('acceptance 10: every published contest result and mutual exhaustion [scenario:10]',()=>{const run=(attack,defense,third=false)=>{const game=gameOf(third?3:2),a=game.addPlayer(),b=game.addPlayer(),c=third?game.addPlayer():null;game.start(a,0);game.start(b,1);if(c)game.start(c,2);const r=game.regions[0];r.inventories.medicine=0;r.protection=defense;r.campaigns[b.id]={medicine:attack,radiotherapy:0,targeted:0,immunotherapy:0,vaccine:0};if(c)r.campaigns[c.id]={medicine:attack,radiotherapy:0,targeted:0,immunotherapy:0,vaccine:0};let seconds=0;while((r.ownerId===a.id||third)&&seconds<30&&Object.keys(r.campaigns).length){game.resolveContests(.25,seconds+.25);seconds+=.25;if(third&&!Object.keys(r.campaigns).length)break;}return {game,a,b,c,r,seconds};};for(const [attack,defense,duration,survivor,attackerWins] of [[60,30,3.25,42.20,true],[120,100,8.5,46.96,true],[80,120,6,72.70,false]]){const x=run(attack,defense);close(x.seconds,duration);close(attackerWins?x.game.defenderForce(x.r):x.r.protection,survivor,.02);assert.equal(x.r.ownerId,attackerWins?x.b.id:x.a.id);}const equal=run(100,100);close(equal.seconds,12.75);assert.equal(equal.r.ownerId,equal.a.id);const three=run(100,100,true);close(three.seconds,12.75);assert.equal(three.r.ownerId,equal.a.id);});
test('acceptance 11: surviving attackers create an ownerless productive dispute [scenario:11]',()=>{const game=gameOf(3),a=game.addPlayer(),b=game.addPlayer(),c=game.addPlayer();game.start(a,0);game.start(b,1);game.start(c,2);const r=game.regions[0];r.inventories.medicine=0;r.protection=.1;r.campaigns[b.id]={medicine:20,radiotherapy:0,targeted:0,immunotherapy:0,vaccine:0};r.campaigns[c.id]={medicine:20,radiotherapy:0,targeted:0,immunotherapy:0,vaccine:0};game.resolveContests(.25,.25);assert.equal(r.ownerId,null);assert.equal(Object.keys(r.campaigns).length,2);});
test('acceptance 12: capture downgrades once and preserves excess winning stock [scenario:12]',()=>{const {game,b}=pair();const r=game.regions[0];r.level=2;r.campaigns[b.id]={medicine:450,radiotherapy:0,targeted:0,immunotherapy:0,vaccine:0};game.capture(r,b.id,1);assert.equal(r.level,1);assert.equal(r.inventories.medicine,450);assert.ok(game.storageUsed(r)>game.storageCap(r));});
test('acceptance 13: capture starts commissioning and dominance from zero [scenario:13]',()=>{const {game,b}=pair();game.elapsed=10;game.capture(game.regions[0],b.id,10);assert.equal(game.regions[0].acquiredAt,10);assert.equal(game.holdSeconds,0);game.economy(b,.25,10,10.25);assert.ok(b.gross<8+2*(3+.4));});
test('acceptance 14: arrivals reset quiet time and regeneration waits beyond five seconds [scenario:14]',()=>{const {game,b}=pair();const r=game.regions[0];r.protection=0;r.quietTime=5;r.campaigns[b.id]={medicine:1,radiotherapy:0,targeted:0,immunotherapy:0,vaccine:0};game.regenerate(.25);assert.equal(r.quietTime,0);delete r.campaigns[b.id];game.regenerate(5);assert.equal(r.protection,0);game.regenerate(.25);assert.ok(r.protection>0);});
test('acceptance 15: continuity consumes ten VAC and uses finite scheduled values [scenario:15]',()=>{const game=gameOf(),p=game.addPlayer();game.start(p,0);p.completed.push('R09');game.regions[0].inventories.vaccine=10;game.activateProgramme(p,0);assert.equal(game.regions[0].inventories.vaccine,0);assert.equal(game.regions[0].programme.completesAt,8);game.expireProgrammes(8);assert.equal(game.regions[0].programme.protection,60);assert.equal(game.regions[0].programme.expiresAt,98);game.regions[0].protection=0;game.regenerate(10);assert.equal(game.regions[0].programme.protection,60);game.expireProgrammes(98);assert.equal(game.regions[0].programme,null);const advanced=gameOf(),q=advanced.addPlayer();advanced.start(q,0);q.completed.push('R09','R10');advanced.regions[0].inventories.vaccine=10;advanced.activateProgramme(q,0);advanced.expireProgrammes(8);assert.equal(advanced.regions[0].programme.protection,75);assert.equal(advanced.regions[0].programme.expiresAt,128);});
test('acceptance 16: same-company terminal arrivals aggregate independent of order [scenario:16]',()=>{const game=gameOf(),p=game.addPlayer();game.start(p,0);const r=game.regions[1];r.ownerId=p.id;r.inventories.medicine=195;for(const units of [10,20])game.convoys.push({id:String(units),companyId:p.id,targetId:1,path:[0,1],index:0,supply:{medicine:units,radiotherapy:0,targeted:0,immunotherapy:0,vaccine:0},capacity:units,edgeTime:3,dueAt:3});game.deliver(3);close(r.inventories.medicine,200);assert.equal(game.arrivalReports.length,1);});
test('acceptance 17: withdrawal retains every treatment at eighty percent once [scenario:17]',()=>{const {game,a}=pair();game.regions[1].campaigns[a.id]={medicine:10,radiotherapy:5,targeted:4,immunotherapy:3,vaccine:2};game.withdraw(a,1,0);for(const [key,value] of Object.entries({medicine:8,radiotherapy:4,targeted:3.2,immunotherapy:2.4,vaccine:1.6}))close(game.convoys[0].supply[key],value);assert.equal(game.regions[1].campaigns[a.id],undefined);});
test('acceptance 18: existing commitments are not removed when capacity shrinks [scenario:18]',()=>{const {game,a}=pair();game.regions[0].inventories.medicine=120;game.dispatch(a,0,1,50,'medicine');a.foreignTargetLimit=0;assert.equal(game.convoys.length,1);game.tick(3);assert.ok(game.regions[1].campaigns[a.id].medicine>0);});
test('acceptance 19: bot thresholds permit 65 percent while retaining reserve [scenario:19]',()=>{assert.deepEqual(BALANCE.bots.packetShares,[.5,.65]);assert.equal(1-BALANCE.bots.packetShares[1]>=BALANCE.bots.retainedShare,true);const {game,a}=pair();a.bot=true;a.programmeObjective=1;assert.doesNotThrow(()=>game.runBotTactical(a));});
test('acceptance 20: surrender changes control while reconnect restores ordinary control [scenario:20]',()=>{const {game,a}=pair();game.removePlayer(a.id);assert.equal(game.reconnectPlayer(a.id),true);assert.equal(a.bot,false);a.surrendered=true;a.bot=true;assert.equal(game.reconnectPlayer(a.id),false);assert.equal(game.regions[0].ownerId,a.id);});
test('acceptance 21: simultaneous ownership exchange preserves a company [scenario:21]',()=>{const {game,a,b}=pair();game.regions[0].ownerId=b.id;game.regions[1].ownerId=a.id;game.eliminate();assert.equal(a.eliminated,false);assert.equal(b.eliminated,false);});
test('acceptance 22: duplicate unauthorized and invalid commands are atomic [scenario:22]',()=>{const {game,a,b}=pair();a.allocation={research:100,manufacturing:0,infrastructure:0};b.allocation={research:100,manufacturing:0,infrastructure:0};const before=structuredClone(game.regions.map(r=>r.inventories));assert.equal(game.handle(a.id,{type:'dispatch',fromId:1,toId:0,commandId:'bad'}),true);game.tick(.25);assert.equal(game.commandLog.at(-1).reason,'unauthorized_source');assert.equal(game.handle(a.id,{type:'dispatch',fromId:0,toId:1,commandId:'bad'}),false);assert.equal(game.lastRejection,'duplicate_command');assert.deepEqual(game.regions.map(r=>r.inventories),before);assert.equal(game.convoys.length,0);assert.ok(treatmentForce(b,'medicine','solid')>0);});
