import { randomUUID } from 'node:crypto';
import { createSeededMap, MAP_TEMPLATES, regionNeighbours } from './map.js';
import { BUDGET_PRESETS, redistributeBudget } from '../public/budget.js';

export const STEP = 0.25;
export const MAP = { columns: 16, rows: 10 };
export const LOBBY_SIZES = MAP_TEMPLATES;
export const PHASES = Object.freeze({ WAITING: 'waiting', PLACEMENT: 'placement', ACTIVE: 'active', FINISHED: 'finished' });
export const PROFILES = ['solid', 'blood', 'rare', 'mixed'];
export const BALANCE_VERSION = '0.2';
export const TREATMENTS = {
  medicine: { id: 'MED', label: 'Basic medicines', cost: 1, level: 0, edgeTime: 3 },
  radiotherapy: { id: 'RAD', label: 'Radiotherapy capacity', cost: 2, level: 1, edgeTime: 5 },
  targeted: { id: 'TGT', label: 'Targeted therapies', cost: 2.5, level: 1, edgeTime: 3 },
  immunotherapy: { id: 'IMM', label: 'Immunotherapy', cost: 3, level: 2, edgeTime: 4 },
  vaccine: { id: 'VAC', label: 'Therapeutic vaccines', cost: 4, level: 2, edgeTime: 5 }
};
export const RESEARCH = {
  R01: ['Manufacturing scale-up', null, 140, 40], R02: ['Optimized protocols', null, 80, 25],
  R03: ['Molecular diagnostics', null, 100, 30], R04: ['Targeted platform', 'R03', 180, 45],
  R05: ['Second indication', 'R04', 360, 120], R06: ['Radiation planning', null, 140, 35],
  R07: ['Image guidance', 'R06', 360, 120], R08: ['Immune engineering', 'R03', 220, 55],
  R09: ['Therapeutic vaccine platform', 'R08', 260, 65], R10: ['Immune memory programme', 'R09', 360, 120],
  R11: ['Cold-chain logistics', 'R01', 140, 35], R12: ['Network scheduling', 'R11', 220, 55]
};
export const DEFAULT_RESEARCH = ['R02','R03','R04','R01','R06','R11','R08','R09','R12','R05','R07','R10'];
const KEYS = Object.keys(TREATMENTS);
const emptyInventory = () => Object.fromEntries(KEYS.map(key => [key, 0]));
const clamp = (n, lo, hi) => Math.max(lo, Math.min(hi, n));
const cleanName = name => String(name ?? '').replace(/[^\p{L}\p{N} ._-]/gu, '').trim().slice(0, 18) || 'Researcher';
const finite = value => Number.isFinite(Number(value));

export function treatmentForce(player, key, profile, defending = false) {
  const base = TREATMENTS[key].cost;
  let multiplier = key === 'radiotherapy' ? ({ solid:1.35,blood:.55,rare:.85,mixed:1 }[profile]) : key === 'immunotherapy' ? (profile === 'mixed' ? 1.35 : 1.25) : key === 'vaccine' ? .7 : 1;
  if (key === 'targeted') multiplier = player.targetedIndications.includes(profile) ? 1.6 : .75;
  if (key === 'medicine' && player.completed.includes('R02')) multiplier *= 1.15;
  if (key === 'medicine' && player.completed.includes('R03') && profile === player.specialty) multiplier *= 1.05;
  if (key === 'radiotherapy' && defending) multiplier *= player.completed.includes('R07') ? 1.3 : 1.15;
  return base * multiplier;
}

export class Game {
  constructor({ random = Math.random, id = randomUUID, matchSeconds = 720, lobbySize = 20, placementSeconds = 20, columns, rows, seed = randomUUID(), now = () => Date.now() } = {}) {
    if (!LOBBY_SIZES[lobbySize] && (columns == null || rows == null)) throw new RangeError('lobbySize must be 20, 30, or 40');
    const template = columns != null && rows != null ? { columns, rows } : LOBBY_SIZES[lobbySize];
    this.random=random; this.id=id; this.now=now; this.matchSeconds=matchSeconds; this.lobbySize=lobbySize; this.placementSeconds=placementSeconds; this.elapsed=0; this.lobbyElapsed=0; this.accumulator=0; this.players=new Map();
    this.phase=PHASES.WAITING; this.placementRemaining=placementSeconds; this.startedAt=null; this.finishedAt=null;
    this.convoys=[]; this.arrivalReports=[]; this.routeInterruptions=[]; this.commands=[]; this.commandLog=[]; this.commandIds=new Set(); this.sequence=0; this.winner=null; this.result=null; this.holdLeader=null; this.holdSeconds=0;
    const generated = columns == null && rows == null ? createSeededMap({ lobbySize, seed }) : null;
    this.seed=String(seed); this.map={ ...template, seed:this.seed }; this.regions=Array.from({length:template.columns*template.rows},(_,id)=>({ id, name:`Region ${id+1}`, column:id%template.columns,row:Math.floor(id/template.columns), neighbours:generated?.regions[id].neighbours??regionNeighbours(id,template.columns,template.rows), profile:generated?.regions[id].profile??PROFILES[id%4], profilePatch:generated?.regions[id].profilePatch??null, ownerId:null, level:0, upgradeProgress:0, inventories:emptyInventory(), protection:30, quietTime:0, acquiredAt:null, commissionedUntil:0, dispatchAvailableAt:0, programme:null, developmentPin:false, productionPin:false, campaigns:{} }));
    this.pads=generated?.pads??Array.from({length:lobbySize},(_,index)=>Math.floor(index*this.regions.length/lobbySize));
    this.contests=new Map();
  }

  addPlayer(name='Researcher', { bot = false, credential } = {}) {
    if (this.players.size >= this.lobbySize) return null;
    const playerId=this.id(); credential??=this.id();
    const inventory=emptyInventory(); inventory.medicine=0;
    const p={ id:playerId,name:cleanName(name),color:`hsl(${Math.floor(this.random()*360)} 70% 58%)`,initials:'',started:false,eliminated:false,bot:false,surrendered:false,specialty:null,focus:null,
      allocation:{...BUDGET_PRESETS.balanced},pendingAllocation:null,researchBank:0,infrastructureBank:0,revenue:0,gross:0,upkeep:0,net:0,research:0,researchQueue:[...DEFAULT_RESEARCH],researchProgress:{},completed:[],priorityAvailableAt:0,targetedIndications:[],selectedTreatment:'medicine',pendingTreatment:null,manufacturingAvailableAt:0,r05Choice:null,r05RequestedChoice:null,
      stock:inventory,unlocked:['medicine'],commitment:50,filter:'all',production:0,manufacturingFunding:0,directManufacturingFunding:0,manufacturingSpend:0,unusedManufacturing:0,researchOverflow:0,infrastructureOverflow:0,overflow:0,regionSeconds:0,productionPin:null,developmentPin:null,researchActive:null,researchEta:null,infrastructureActive:null,infrastructureReason:null,infrastructureEta:null,
      connected:!bot,disconnectedAt:null,nextBotAt:0,researchSpend:0,infrastructureSpend:0,manufacturingSpend:0,credential,spectator:false };
    p.bot=bot;
    p.initials=p.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase(); this.players.set(p.id,p); return p;
  }
  connect(name='Researcher') {
    if (this.phase===PHASES.ACTIVE||this.phase===PHASES.FINISHED||this.players.size>=this.lobbySize) return { spectator:true, player:null, credential:null };
    const player=this.addPlayer(name); if(this.phase===PHASES.WAITING){this.phase=PHASES.PLACEMENT;this.placementRemaining=this.placementSeconds;} return { spectator:false,player,credential:player.credential };
  }
  reconnect(credential){const p=[...this.players.values()].find(x=>x.credential===credential);if(!p||!this.reconnectPlayer(p.id))return null;return p;}
  removePlayer(id) { const p=this.players.get(id); if (!p) return false; p.connected=false;p.disconnectedAt=this.elapsed;return true; }
  reconnectPlayer(id) { const p=this.players.get(id);if(!p||p.surrendered)return false;p.connected=true;p.disconnectedAt=null;p.bot=false;return true; }
  renamePlayer(p,name){p.name=cleanName(name);p.initials=p.name.slice(0,2).toUpperCase();return true;}
  adjacent(a,b){ return Boolean(this.regions[Number(a)]?.neighbours.includes(Number(b))); }
  owned(p){return this.regions.filter(r=>r.ownerId===p.id);}
  unlocks(p){return ['medicine',...(p.completed.includes('R06')?['radiotherapy']:[]),...(p.completed.includes('R04')?['targeted']:[]),...(p.completed.includes('R08')?['immunotherapy']:[]),...(p.completed.includes('R09')?['vaccine']:[])];}

  handle(id,message,receivedAt=this.now()){ const p=this.players.get(id); if(!p||!message||typeof message!=='object')return this.reject('invalid_command');
    if(typeof message.commandId!=='string'||!message.commandId.trim())return this.reject('missing_command_id');
    if(this.commandIds.has(`${id}:${message.commandId}`))return this.rejectLogged(id,message,receivedAt,'duplicate_command');this.commandIds.add(`${id}:${message.commandId}`);
    if(this.phase===PHASES.FINISHED)return this.rejectLogged(id,message,receivedAt,'match_finished');
    const actions={join:()=>this.renamePlayer(p,message.name),start:()=>this.start(p,message.regionId,message.specialty),allocate:()=>this.allocate(p,message.allocation),budget:()=>this.changeBudget(p,message.category,message.value),budgetPreset:()=>this.applyBudgetPreset(p,message.preset),selectTreatment:()=>this.selectTreatment(p,message.treatment),dispatchPreferences:()=>this.setDispatchPreferences(p,message.commitment,message.filter),contest:()=>this.dispatch(p,message.fromId,message.toId,message.commitment,message.filter),dispatch:()=>this.dispatch(p,message.fromId,message.toId,message.commitment,message.filter),withdraw:()=>this.withdraw(p,message.regionId,message.toId),research:()=>this.prioritizeResearch(p,message.project,message.indication),programme:()=>this.activateProgramme(p,message.regionId),pin:()=>this.setPin(p,message.kind,message.regionId),surrender:()=>{p.surrendered=true;p.bot=true;return true;}};
    const placement=message.type==='start', lobby=message.type==='join';
    if(placement&&this.phase!==PHASES.PLACEMENT)return this.rejectLogged(id,message,receivedAt,'invalid_phase');
    if(!placement&&!lobby&&this.phase!==PHASES.ACTIVE)return this.rejectLogged(id,message,receivedAt,'invalid_phase');
    if((p.eliminated||p.bot)&&!lobby)return this.rejectLogged(id,message,receivedAt,'not_human_controlled');
    if(lobby)return actions.join();
    const envelope={companyId:id,commandId:message.commandId,receivedAt,sequence:++this.sequence,message:{...message},status:'accepted'};
    this.commands.push(envelope);this.commandLog.push(envelope);return true;
  }
  reject(reason){this.lastRejection=reason;return false;}
  rejectLogged(companyId,message,receivedAt,reason){this.lastRejection=reason;this.commandLog.push({companyId,commandId:message.commandId,receivedAt,sequence:++this.sequence,type:message.type,status:'rejected',reason,processedAt:this.phase===PHASES.ACTIVE?this.elapsed:this.lobbyElapsed});return false;}
  start(p,id,specialty,requirePad=false){const r=this.regions[Number(id)];if(p.started||!r||r.ownerId!==null||(requirePad&&!this.pads.includes(r.id)))return this.reject('invalid_start');r.ownerId=p.id;r.level=1;r.protection=35;r.inventories.medicine=120;r.acquiredAt=this.elapsed;p.started=true;p.specialty=PROFILES.includes(specialty)?specialty:r.profile;p.focus=p.specialty;if(!requirePad&&this.phase===PHASES.WAITING){this.phase=PHASES.ACTIVE;this.startedAt=this.now();}return true;}
  allocate(p,a){if(!a||Object.keys(a).length!==3||!['research','manufacturing','infrastructure'].every(k=>finite(a[k])&&Number(a[k])%5===0&&Number(a[k])>=0))return this.reject('invalid_budget');const values=Object.values(a).map(Number);if(values.reduce((x,y)=>x+y,0)!==100)return this.reject('invalid_budget_total');p.pendingAllocation={research:+a.research,manufacturing:+a.manufacturing,infrastructure:+a.infrastructure};return true;}
  changeBudget(p,category,value){const allocation=redistributeBudget(p.pendingAllocation??p.allocation,category,Number(value));return allocation?this.allocate(p,allocation):this.reject('invalid_budget');}
  applyBudgetPreset(p,name){const preset=BUDGET_PRESETS[name];return preset?this.allocate(p,preset):this.reject('invalid_budget_preset');}
  selectTreatment(p,key){if(!this.unlocks(p).includes(key))return this.reject('locked_treatment');if(p.pendingTreatment||this.elapsed<p.manufacturingAvailableAt)return this.reject('manufacturing_switching');if(p.selectedTreatment===key)return true;p.pendingTreatment=key;p.manufacturingAvailableAt=this.elapsed+5;return true;}
  path(from,to,owner){const queue=[[from]],seen=new Set([from]);while(queue.length){const path=queue.shift(),last=path.at(-1);if(last===to)return path;for(const n of this.regions[last].neighbours)if(!seen.has(n)&&(n===to||this.regions[n].ownerId===owner)){seen.add(n);queue.push([...path,n]);}}return null;}
  setDispatchPreferences(p,commitment=p.commitment,filter=p.filter){const percent=Number(commitment);if(!finite(percent)||percent<10||percent>100||percent%5)return this.reject('invalid_commitment');if(filter!=='all'&&!KEYS.includes(filter))return this.reject('invalid_filter');p.commitment=percent;p.filter=filter;return true;}
  dispatch(p,fromId,toId,commitment=p.commitment,filter=p.filter){
    const from=this.regions[Number(fromId)],to=this.regions[Number(toId)],percent=Number(commitment);if(!p.started||p.eliminated||!from||!to||from.ownerId!==p.id)return this.reject('unauthorized_source');if(!finite(percent)||percent<10||percent>100||percent%5)return this.reject('invalid_commitment');if(this.elapsed<from.dispatchAvailableAt)return this.reject('dispatch_cooldown');if(this.convoys.filter(c=>c.companyId===p.id).length>=16)return this.reject('convoy_limit');
    const path=to.ownerId===p.id?this.path(from.id,to.id,p.id):(this.adjacent(from.id,to.id)?[from.id,to.id]:null);if(!path||path.length<2)return this.reject('no_route');
    const chosen=filter==='all'?KEYS:[filter];if(!chosen.every(k=>KEYS.includes(k)))return this.reject('invalid_filter');const supply=emptyInventory();for(const k of chosen)supply[k]=from.inventories[k]*percent/100;const capacity=KEYS.reduce((s,k)=>s+supply[k]*TREATMENTS[k].cost,0);if(capacity<10)return this.reject('packet_too_small');if(to.ownerId!==p.id){const foreign=this.foreignTargets(p);const reserved=Math.min(6,3+Math.floor(this.owned(p).length/16));if(!foreign.has(to.id)&&foreign.size>=reserved)return this.reject('foreign_target_limit');if(this.targetCommitment(p.id,to.id)+capacity>1000)return this.reject('target_capacity');}
    for(const k of KEYS)from.inventories[k]-=supply[k];const slow=Math.max(...chosen.filter(k=>supply[k]>0).map(k=>TREATMENTS[k].edgeTime));const edgeTime=slow*(p.completed.includes('R11')?.8:1);this.convoys.push({id:this.id(),companyId:p.id,sourceId:from.id,targetId:to.id,path,index:0,supply,capacity,edgeTime,dueAt:this.elapsed+edgeTime,createdAt:this.elapsed});from.dispatchAvailableAt=this.elapsed+1;return true;
  }
  foreignTargets(p){const targets=new Set(this.convoys.filter(c=>c.companyId===p.id&&this.regions[c.targetId]?.ownerId!==p.id).map(c=>c.targetId));for(const r of this.regions)if(r.ownerId!==p.id&&r.campaigns[p.id])targets.add(r.id);return targets;}
  targetCommitment(companyId,targetId){let total=this.convoys.filter(c=>c.companyId===companyId&&c.targetId===targetId).reduce((s,c)=>s+c.capacity,0);const campaign=this.regions[targetId]?.campaigns[companyId];if(campaign)total+=KEYS.reduce((s,k)=>s+campaign[k]*TREATMENTS[k].cost,0);return total;}
  contest(p,from,to,commitment){return this.dispatch(p,from,to,commitment,p.selectedTreatment);}
  withdraw(p,regionId,toId){const r=this.regions[Number(regionId)],to=this.regions[Number(toId)],campaign=r?.campaigns[p.id];if(!campaign||to?.ownerId!==p.id||!this.adjacent(r.id,to.id))return this.reject('invalid_withdrawal');if(this.convoys.filter(c=>c.companyId===p.id).length>=16)return this.reject('convoy_limit');const supply=emptyInventory();for(const k of KEYS)supply[k]=campaign[k]*.8;const edgeTime=(Math.max(...KEYS.filter(k=>supply[k]>0).map(k=>TREATMENTS[k].edgeTime))||3)*(p.completed.includes('R11')?.8:1);const capacity=KEYS.reduce((s,k)=>s+supply[k]*TREATMENTS[k].cost,0);delete r.campaigns[p.id];this.convoys.push({id:this.id(),companyId:p.id,sourceId:r.id,targetId:to.id,path:[r.id,to.id],index:0,supply,capacity,edgeTime,dueAt:this.elapsed+edgeTime,createdAt:this.elapsed});return true;}
  prioritizeResearch(p,id,indication){if(!RESEARCH[id]||p.completed.includes(id)||this.elapsed<p.priorityAvailableAt)return this.reject('invalid_research_priority');if(indication!=null){if(id!=='R05'||p.r05Choice||!PROFILES.includes(indication)||indication===p.specialty)return this.reject('invalid_r05_indication');p.r05RequestedChoice=indication;}const chain=[];let x=id;while(x&&!p.completed.includes(x)){chain.unshift(x);x=RESEARCH[x][1];}p.researchQueue=[...chain,...p.researchQueue.filter(q=>!chain.includes(q)&&!p.completed.includes(q))];p.priorityAvailableAt=this.elapsed+5;return true;}
  activateProgramme(p,id){const r=this.regions[Number(id)];if(!p.completed.includes('R09')||r?.ownerId!==p.id||r.programme||r.inventories.vaccine<10)return this.reject('invalid_programme');r.inventories.vaccine-=10;r.programme={pending:true,companyId:p.id,completesAt:this.elapsed+8,expiresAt:null,protection:0};return true;}
  setPin(p,kind,id){const r=this.regions[Number(id)];if(r?.ownerId!==p.id||!['production','development'].includes(kind))return false;p[`${kind}Pin`]=r.id;return true;}

  tick(seconds=STEP){if(this.phase===PHASES.FINISHED)return;this.accumulator+=clamp(Number(seconds)||0,0,5);while(this.accumulator+1e-9>=STEP&&this.phase!==PHASES.FINISHED){this.step();this.accumulator-=STEP;}}
  processCommands(){const queued=this.commands.splice(0).sort((a,b)=>a.sequence-b.sequence);for(const envelope of queued){const p=this.players.get(envelope.companyId),m=envelope.message;let ok=false;if(!p) this.lastRejection='unknown_company';else if(m.type==='start')ok=this.phase===PHASES.PLACEMENT&&this.start(p,m.regionId,m.specialty,true);else if(this.phase!==PHASES.ACTIVE)this.lastRejection='invalid_phase';else if(p.eliminated||p.bot)this.lastRejection='not_human_controlled';else {const actions={allocate:()=>this.allocate(p,m.allocation),budget:()=>this.changeBudget(p,m.category,m.value),budgetPreset:()=>this.applyBudgetPreset(p,m.preset),selectTreatment:()=>this.selectTreatment(p,m.treatment),dispatchPreferences:()=>this.setDispatchPreferences(p,m.commitment,m.filter),contest:()=>this.dispatch(p,m.fromId,m.toId,m.commitment,m.filter),dispatch:()=>this.dispatch(p,m.fromId,m.toId,m.commitment,m.filter),withdraw:()=>this.withdraw(p,m.regionId,m.toId),research:()=>this.prioritizeResearch(p,m.project,m.indication),programme:()=>this.activateProgramme(p,m.regionId),pin:()=>this.setPin(p,m.kind,m.regionId),surrender:()=>{p.surrendered=true;p.bot=true;return true;}};ok=actions[m.type]?.()??this.reject('unknown_command');}envelope.status=ok?'applied':'rejected';envelope.processedAt=this.phase===PHASES.ACTIVE?this.elapsed:this.lobbyElapsed;envelope.reason=ok?null:this.lastRejection;}}
  beginMatch(){const vacant=this.lobbySize-this.players.size;for(let i=0;i<vacant;i++)this.addPlayer(`Automated ${String(i+1).padStart(2,'0')}`,{bot:true});const freePads=this.pads.filter(id=>this.regions[id].ownerId===null);const unplaced=[...this.players.values()].filter(p=>!p.started).sort((a,b)=>a.id.localeCompare(b.id));unplaced.forEach((p,index)=>this.start(p,freePads[index]));this.phase=PHASES.ACTIVE;this.elapsed=0;this.startedAt=this.now();for(const p of this.players.values())p.nextBotAt=0;}
  step(){this.processCommands();if(this.phase===PHASES.WAITING)return;if(this.phase===PHASES.PLACEMENT){this.lobbyElapsed+=STEP;this.placementRemaining=Math.max(0,this.placementSeconds-this.lobbyElapsed);if(this.placementRemaining<=0||this.players.size===this.lobbySize)this.beginMatch();return;}const start=this.elapsed,end=Math.min(this.matchSeconds,start+STEP),dt=end-start;if(dt<=0){this.checkVictory(0);return;}for(const p of this.players.values()){if(!p.connected&&!p.surrendered&&p.disconnectedAt!=null&&start-p.disconnectedAt>=30)p.bot=true;if(p.pendingAllocation){p.allocation=p.pendingAllocation;p.pendingAllocation=null;}if(p.pendingTreatment&&start+1e-9>=p.manufacturingAvailableAt){p.selectedTreatment=p.pendingTreatment;p.pendingTreatment=null;}}this.deliver(end);this.expireProgrammes(end);for(const p of this.players.values())if(p.started&&!p.eliminated)this.economy(p,dt,start,end);this.regenerate(dt);this.resolveContests(dt,end);this.elapsed=end;this.applyCompletions();this.clearInvalidPins();this.eliminate();this.runBots();this.checkVictory(dt);}
  economy(p,dt,start,end){const owned=this.owned(p);p.regionSeconds+=owned.length*dt;let gross=8;let operating=0;for(const r of owned){let mult=1;if(r.acquiredAt!=null&&r.acquiredAt>0){const commissioned=Math.max(0,Math.min(end,r.acquiredAt+10)-start);mult=1-.5*commissioned/dt;}gross+=mult*(3+.4*r.level);operating+=1+.1*r.level;}const d=Math.max(0,owned.length-8),admin=(p.completed.includes('R12')?.85:1)*1.5*owned.length*d/(d+20);p.gross=gross;p.upkeep=operating+admin;p.net=Math.max(0,gross-p.upkeep);p.revenue+=p.net*dt;
    const alloc=p.allocation,rf=p.net*dt*alloc.research/100,ipf=p.net*dt*alloc.infrastructure/100,mf=p.net*dt*alloc.manufacturing/100;const beforeResearch=p.research,researchOverflow=this.fundResearch(p,rf,dt),beforeInfrastructure=this.totalUpgradeProgress(p),infrastructureOverflow=this.fundInfrastructure(p,ipf,dt);p.researchSpend=(p.research-beforeResearch)/dt;p.infrastructureSpend=(this.totalUpgradeProgress(p)-beforeInfrastructure)/dt;p.directManufacturingFunding=mf/dt;p.researchOverflow=researchOverflow/dt;p.infrastructureOverflow=infrastructureOverflow/dt;p.overflow=p.researchOverflow+p.infrastructureOverflow;p.manufacturingFunding=(mf+researchOverflow+infrastructureOverflow)/dt;this.manufacture(p,mf+researchOverflow+infrastructureOverflow,dt,owned);this.updateSchedulingFeedback(p);}
  totalUpgradeProgress(p){return this.owned(p).reduce((sum,r)=>sum+r.upgradeProgress,0);}
  activeResearch(p){return p.researchQueue.find(id=>!p.completed.includes(id)&&(!RESEARCH[id][1]||p.completed.includes(RESEARCH[id][1])));}
  fundResearch(p,funding,dt){const id=this.activeResearch(p);if(!id){const total=p.researchBank+funding;p.researchBank=Math.min(300,total);return Math.max(0,total-300);}const [, ,cost,minTime]=RESEARCH[id],progress=p.researchProgress[id]||0,available=p.researchBank+funding,spend=Math.min(available,cost-progress,cost/minTime*dt);if(id==='R05'&&spend>0&&!p.r05Choice)p.r05Choice=p.r05RequestedChoice??this.defaultR05Choice(p);p.researchProgress[id]=progress+spend;p.research+=spend;p.researchBank=Math.min(300,available-spend);return Math.max(0,available-spend-300);}
  defaultR05Choice(p){const eligible=PROFILES.filter(profile=>profile!==p.specialty),counts=Object.fromEntries(eligible.map(profile=>[profile,0]));for(const r of this.regions)if(r.ownerId!==p.id&&r.neighbours.some(n=>this.regions[n].ownerId===p.id)&&counts[r.profile]!=null)counts[r.profile]++;if(Math.max(...Object.values(counts))===0)for(const r of this.regions)if(counts[r.profile]!=null)counts[r.profile]++;return eligible.sort((a,b)=>counts[b]-counts[a]||PROFILES.indexOf(a)-PROFILES.indexOf(b))[0];}
  infrastructureTarget(p){const owned=this.owned(p),unfinished=owned.filter(r=>r.level<3),sort=(a,b)=>a.level-b.level||(a.acquiredAt??Infinity)-(b.acquiredAt??Infinity)||a.id-b.id,pinned=unfinished.find(r=>r.id===p.developmentPin);if(pinned)return {region:pinned,reason:'development pin'};const capable=unfinished.filter(r=>r.level>=TREATMENTS[p.selectedTreatment].level).sort(sort);if(capable[0])return {region:capable[0],reason:`supports ${TREATMENTS[p.selectedTreatment].id}`};const fallback=unfinished.sort(sort)[0];return fallback?{region:fallback,reason:'lowest level, then acquisition and ID'}:null;}
  fundInfrastructure(p,funding,dt){const target=this.infrastructureTarget(p),r=target?.region;if(!r){const total=p.infrastructureBank+funding;p.infrastructureBank=Math.min(300,total);return Math.max(0,total-300);}const costs=[0,60,140,260],times=[0,20,35,50],cost=costs[r.level+1],available=p.infrastructureBank+funding,spend=Math.min(available,cost-r.upgradeProgress,cost/times[r.level+1]*dt);r.upgradeProgress+=spend;p.infrastructureBank=Math.min(300,available-spend);return Math.max(0,available-spend-300);}
  manufacture(p,funding,dt,owned){const key=p.selectedTreatment,t=TREATMENTS[key],efficiency=p.completed.includes('R01')?1.1:1,eligible=owned.filter(r=>r.level>=t.level&&this.storageUsed(r)<this.storageCap(r));let remaining=funding,accepted=0;const weighted=eligible.map(r=>({r,w:(p.productionPin===r.id?3:1)*(r.neighbours.some(n=>this.regions[n].ownerId!==p.id)?3:1),used:0}));while(remaining>1e-9){const active=weighted.filter(x=>(4+4*x.r.level)*dt-x.used>1e-9&&this.storageCap(x.r)-this.storageUsed(x.r)>1e-9);if(!active.length)break;const total=active.reduce((s,x)=>s+x.w,0),before=remaining;for(const x of active){const share=before*x.w/total,room=(this.storageCap(x.r)-this.storageUsed(x.r))/efficiency,cap=(4+4*x.r.level)*dt-x.used,take=Math.min(share,cap,room);x.used+=take;x.r.inventories[key]+=take*efficiency/t.cost;remaining-=take;accepted+=take;}if(before-remaining<1e-9)break;}
    p.production=accepted*efficiency/t.cost/dt;p.manufacturingSpend=accepted/dt;p.unusedManufacturing=remaining/dt;}
  updateSchedulingFeedback(p){const active=this.activeResearch(p);p.researchActive=active??null;if(active){const project=RESEARCH[active],remaining=project[2]-(p.researchProgress[active]||0);p.researchEta=p.researchSpend>0?remaining/p.researchSpend:null;}else p.researchEta=null;const target=this.infrastructureTarget(p);p.infrastructureActive=target?.region.id??null;p.infrastructureReason=target?.reason??'all regions fully developed';if(target){const costs=[0,60,140,260],remaining=costs[target.region.level+1]-target.region.upgradeProgress;p.infrastructureEta=p.infrastructureSpend>0?remaining/p.infrastructureSpend:null;}else p.infrastructureEta=null;}
  storageCap(r){return 200+100*r.level;} storageUsed(r){return KEYS.reduce((s,k)=>s+r.inventories[k]*TREATMENTS[k].cost,0);}
  deliver(time){const arrivals=[];for(const c of this.convoys)while(c.dueAt<=time+1e-9){const current=c.path[c.index];if(c.index>0&&current!==c.targetId&&this.regions[current].ownerId!==c.companyId){c.interrupted=true;arrivals.push(c);break;}const next=c.path[c.index+1];if(next==null){arrivals.push(c);break;}c.index++;if(next===c.targetId||this.regions[next].ownerId!==c.companyId){if(next!==c.targetId)c.interrupted=true;arrivals.push(c);break;}c.dueAt+=c.edgeTime;}const groups=new Map();for(const c of arrivals){this.convoys.splice(this.convoys.indexOf(c),1);const regionId=c.path[c.index],key=`${regionId}:${c.companyId}`;if(c.interrupted)this.routeInterruptions.push({id:`${c.id}:${regionId}`,convoyId:c.id,companyId:c.companyId,regionId,at:time});if(!groups.has(key))groups.set(key,{region:this.regions[regionId],companyId:c.companyId,supply:emptyInventory(),convoyIds:[]});const group=groups.get(key);group.convoyIds.push(c.id);for(const k of KEYS)group.supply[k]+=c.supply[k];}for(const {region:r,companyId,supply,convoyIds} of groups.values()){const incoming=KEYS.reduce((s,k)=>s+supply[k]*TREATMENTS[k].cost,0);let admitted=incoming;if(r.ownerId===companyId)admitted=this.unload(r,supply);else{r.campaigns[companyId]??=emptyInventory();for(const k of KEYS)r.campaigns[companyId][k]+=supply[k];r.quietTime=0;}this.arrivalReports.push({id:`${companyId}:${r.id}:${time}`,companyId,regionId:r.id,convoyIds,incomingCapacity:incoming,admittedCapacity:admitted,discardedCapacity:incoming-admitted,disposition:incoming>admitted?'excess_discarded':'admitted',at:time});}this.arrivalReports=this.arrivalReports.slice(-100);this.routeInterruptions=this.routeInterruptions.slice(-100);this.syncContests();}
  unload(r,supply){const free=Math.max(0,this.storageCap(r)-this.storageUsed(r)),incoming=KEYS.reduce((s,k)=>s+supply[k]*TREATMENTS[k].cost,0),admitted=Math.min(free,incoming),scale=incoming?admitted/incoming:0;for(const k of KEYS)r.inventories[k]+=supply[k]*scale;return admitted;}
  expireProgrammes(time){for(const r of this.regions)if(r.programme){if(r.ownerId!==r.programme.companyId){r.programme=null;continue;}if(r.programme.pending&&r.programme.completesAt<=time){const p=this.players.get(r.ownerId),advanced=p?.completed.includes('R10');r.programme.pending=false;r.programme.protection=advanced?75:60;r.programme.expiresAt=r.programme.completesAt+(advanced?120:90);}if(!r.programme.pending&&r.programme.expiresAt<=time)r.programme=null;}}
  regenerate(dt){for(const r of this.regions){if(Object.keys(r.campaigns).some(id=>this.campaignForce(r,id)>0)){r.quietTime=0;continue;}r.quietTime+=dt;if(r.quietTime>5)r.protection=Math.min(r.ownerId?20+15*r.level:30,r.protection+(r.ownerId?2+r.level:2)*dt);}}
  campaignForce(r,id){const p=this.players.get(id);return p?KEYS.reduce((s,k)=>s+r.campaigns[id][k]*treatmentForce(p,k,r.profile),0):0;}
  defenderForce(r){const p=this.players.get(r.ownerId);return r.protection+(r.programme?.protection||0)+(p?KEYS.reduce((s,k)=>s+r.inventories[k]*treatmentForce(p,k,r.profile,true),0):0);}
  resolveContests(dt,time){const changes=[];for(const r of this.regions){let parties=[];const df=this.defenderForce(r);if(df>0)parties.push({id:r.ownerId??'neutral',defender:true,force:df});for(const id of Object.keys(r.campaigns)){const f=this.campaignForce(r,id);if(f>0)parties.push({id,defender:false,force:f});}if(parties.length<2){if(parties.length===1&&!parties[0].defender)changes.push({r,winner:parties[0].id});continue;}const losses=new Map();for(const target of parties){let loss=0;for(const source of parties)if(source!==target){const others=parties.reduce((s,x)=>s+(x!==source?x.force:0),0);loss+=(.1*source.force+Math.min(4,source.force))*target.force/others;}losses.set(target,Math.min(target.force,loss*dt));}for(const party of parties){const remain=party.force-losses.get(party);if(party.defender)this.consumeDefense(r,losses.get(party)+(remain<1?Math.max(0,remain):0));else this.consumeCampaign(r,party.id,losses.get(party)+(remain<1?Math.max(0,remain):0));party.remain=remain<1?0:remain;}const defender=parties.find(x=>x.defender),attackers=parties.filter(x=>!x.defender&&x.remain>0);if(defender?.remain>0)continue;if(attackers.length===1)changes.push({r,winner:attackers[0].id});else if(attackers.length>1)changes.push({r,winner:null,disputed:true});}
    for(const change of changes)this.capture(change.r,change.winner,time,change.disputed);this.syncContests();}
  consumeDefense(r,loss){let left=loss;if(r.programme){const x=Math.min(left,r.programme.protection);r.programme.protection-=x;left-=x;}const base=Math.min(left,r.protection);r.protection-=base;left-=base;if(left>0){const p=this.players.get(r.ownerId),force=KEYS.reduce((s,k)=>s+r.inventories[k]*(p?treatmentForce(p,k,r.profile,true):1),0),ratio=force?Math.min(1,left/force):0;for(const k of KEYS)r.inventories[k]*=1-ratio;}}
  consumeCampaign(r,id,loss){const force=this.campaignForce(r,id);if(!force)return;const ratio=Math.min(1,loss/force);for(const k of KEYS)r.campaigns[id][k]*=1-ratio;if(this.campaignForce(r,id)<1)delete r.campaigns[id];}
  capture(r,winner,time,disputed=false){const old=r.ownerId;if(winner===old)return;const supply=winner?r.campaigns[winner]:null;r.ownerId=winner;r.upgradeProgress=0;r.inventories=emptyInventory();r.protection=0;r.programme=null;r.quietTime=0;r.disputed=disputed;if(disputed){r.acquiredAt=null;return;}r.level=Math.max(0,r.level-1);if(supply)r.inventories={...supply};r.campaigns={};r.acquiredAt=winner?time:null;r.dispatchAvailableAt=time+5;}
  syncContests(){this.contests.clear();for(const r of this.regions)for(const id of Object.keys(r.campaigns))this.contests.set(`${r.id}:${id}`,{regionId:r.id,attackerId:id,power:this.campaignForce(r,id),defense:this.defenderForce(r)});}
  applyCompletions(){for(const p of this.players.values()){for(const id of Object.keys(p.researchProgress))if(!p.completed.includes(id)&&p.researchProgress[id]>=RESEARCH[id][2]-1e-8){p.completed.push(id);if(id==='R04'&&!p.targetedIndications.includes(p.specialty))p.targetedIndications.push(p.specialty);if(id==='R05'&&p.r05Choice&&!p.targetedIndications.includes(p.r05Choice))p.targetedIndications.push(p.r05Choice);p.unlocked=this.unlocks(p);}}for(const r of this.regions){const costs=[0,60,140,260];if(r.level<3&&r.upgradeProgress>=costs[r.level+1]-1e-8){r.level++;r.upgradeProgress=0;}}}
  clearInvalidPins(){for(const p of this.players.values())for(const kind of ['production','development'])if(this.regions[p[`${kind}Pin`]]?.ownerId!==p.id)p[`${kind}Pin`]=null;}
  eliminate(){for(const p of this.players.values())if(p.started&&!p.eliminated&&!this.regions.some(r=>r.ownerId===p.id)){p.eliminated=true;this.convoys=this.convoys.filter(c=>c.companyId!==p.id);for(const r of this.regions)delete r.campaigns[p.id];}}
  runBots(){for(const p of this.players.values()){if(!p.bot||p.eliminated||!p.started||this.elapsed+1e-9<p.nextBotAt)continue;p.nextBotAt=this.elapsed+2;p.allocation={research:20,manufacturing:65,infrastructure:15};const borders=this.owned(p).filter(r=>r.neighbours.some(n=>this.regions[n].ownerId!==p.id)).sort((a,b)=>a.id-b.id);for(const from of borders){const target=from.neighbours.map(id=>this.regions[id]).filter(r=>r.ownerId!==p.id).sort((a,b)=>a.id-b.id)[0];if(!target)continue;const own=this.defenderForce(from),enemy=this.defenderForce(target);const commitment=own*.5>=30?50:own*.35>=30?65:null;if(commitment&&own*commitment/100>=enemy*(target.ownerId?1.6:1.35)&&this.dispatch(p,from.id,target.id,commitment,'all'))break;}}}
  checkVictory(dt){const alive=[...this.players.values()].filter(p=>p.started&&!p.eliminated),counts=alive.map(p=>({player:p,count:this.owned(p).length})).sort((a,b)=>b.count-a.count||b.player.regionSeconds-a.player.regionSeconds||a.player.id.localeCompare(b.player.id));if(alive.length===1&&[...this.players.values()].filter(p=>p.started).length>1){this.finish([alive[0]],'last-standing');return;}const leader=counts[0],threshold=Math.ceil(.6*this.regions.length);if(leader?.count>=threshold){if(this.holdLeader===leader.player.id)this.holdSeconds+=dt;else{this.holdLeader=leader.player.id;this.holdSeconds=0;}if(this.holdSeconds>=60){this.finish([leader.player],'dominance');return;}}else{this.holdLeader=null;this.holdSeconds=0;}if(this.elapsed>=this.matchSeconds&&leader?.count>0){const winners=counts.filter(x=>x.count===leader.count&&Math.abs(x.player.regionSeconds-leader.player.regionSeconds)<1e-9).map(x=>x.player);this.finish(winners,'timed');}}
  finish(players,type){const winners=Array.isArray(players)?players:[players];this.winner=winners[0].id;this.result={type,winners:winners.map(p=>p.id),at:this.elapsed};this.phase=PHASES.FINISHED;this.finishedAt=this.now();}
  snapshot(){return {version:BALANCE_VERSION,seed:this.seed,phase:this.phase,lobbySize:this.lobbySize,placementRemaining:this.placementRemaining,pads:this.pads,availablePads:this.pads.filter(id=>this.regions[id].ownerId===null),reservedPads:this.pads.filter(id=>this.regions[id].ownerId!==null),map:this.map,profiles:PROFILES,treatments:TREATMENTS,research:RESEARCH,elapsed:this.elapsed,remaining:Math.max(0,this.matchSeconds-this.elapsed),winner:this.winner,result:this.result,hold:{playerId:this.holdLeader,seconds:this.holdSeconds},commandOutcomes:this.commandLog.slice(-100).map(({message,...entry})=>({...entry,type:entry.type??message?.type})),players:[...this.players.values()].map(({credential,...p})=>({...p,dispatchStatus:{convoySlotsUsed:this.convoys.filter(c=>c.companyId===p.id).length,convoySlots:16,foreignTargetsUsed:this.foreignTargets(p).size,foreignTargetSlots:Math.min(6,3+Math.floor(this.owned(p).length/16)),targetCommitments:Object.fromEntries(this.regions.map(r=>[r.id,this.targetCommitment(p.id,r.id)]).filter(([,value])=>value>0))}})),regions:this.regions,convoys:this.convoys,contests:[...this.contests.values()],arrivalReports:this.arrivalReports,routeInterruptions:this.routeInterruptions,leaderboard:[...this.players.values()].map(p=>({id:p.id,name:p.name,color:p.color,regions:this.owned(p).length,regionSeconds:p.regionSeconds})).sort((a,b)=>b.regions-a.regions||b.regionSeconds-a.regionSeconds||a.name.localeCompare(b.name)).slice(0,10)};}
}
